package day4Homework2;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.12.10.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



public interface CQPIServiceEvents
{
    void Starting();
    void Completed(CQPOperationResult result);
}
